# -*- coding: utf-8 -*-
"""Sales_Business_Analysis_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDts11X6QJ2JHN_XtpGYMp39NcfasQ2o
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("Sample - Superstore.csv", encoding="latin1")

df.head()

df.shape

df.info()

df.isnull().sum()

df.drop_duplicates(inplace=True)

df.shape

df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

df["Year"] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month

total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()
total_orders = df["Order ID"].nunique()

print("Total Sales:", total_sales)
print("Total Profit:", total_profit)
print("Total Orders:", total_orders)

df.groupby("Category")[["Sales","Profit"]].sum()

df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(10)

df.groupby("Month")["Sales"].sum()

import matplotlib.pyplot as plt

df.groupby("Month")["Sales"].sum().plot(kind="line")

plt.title("Monthly Sales Trend")
plt.show()

!pip install pandasql

from pandasql import sqldf

pysqldf = lambda q: sqldf(q, globals())

query = """
SELECT
    Year,
    Month,
    SUM(Sales) AS total_sales,
    SUM(Profit) AS total_profit
FROM df
GROUP BY Year, Month
ORDER BY Year, Month
"""

monthly_performance = pysqldf(query)
monthly_performance.head()

query = """
SELECT
    Category,
    SUM(Profit) AS total_profit
FROM df
GROUP BY Category
ORDER BY total_profit DESC
LIMIT 5
"""

pysqldf(query)

query = """
SELECT
    Region,
    SUM(Sales) AS total_sales,
    SUM(Profit) AS total_profit
FROM df
GROUP BY Region
ORDER BY total_sales DESC
"""

pysqldf(query)

query = """
SELECT
    `Customer Name`,
    SUM(Sales) AS total_sales
FROM df
GROUP BY `Customer Name`
ORDER BY total_sales DESC
LIMIT 10
"""

pysqldf(query)

query = """
SELECT
    `Sub-Category`,
    SUM(Profit) AS total_profit
FROM df
GROUP BY `Sub-Category`
HAVING total_profit < 0
ORDER BY total_profit
"""

pysqldf(query)

import matplotlib.pyplot as plt

region_sales = df.groupby("Region")["Sales"].sum()

region_sales.plot(kind="bar")

plt.title("Sales by Region")
plt.xlabel("Region")
plt.ylabel("Total Sales")
plt.show()

category_profit = df.groupby("Category")["Profit"].sum()

category_profit.plot(kind="bar")

plt.title("Profit by Category")
plt.show()

df["Profit Margin"] = df["Profit"] / df["Sales"]

df.groupby("Category")["Profit Margin"].mean()

"""# **Key Business Insights**

• Technology category generates the highest profit.

• Sales increase significantly toward the end of the year.

• A small group of customers contributes a large share of revenue.

• Some sub-categories generate losses despite strong sales.

• Regional sales performance varies significantly.
"""

df.to_csv("clean_superstore.csv", index=False)

from google.colab import files
files.download("clean_superstore.csv")